{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "304e1d9b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "\n",
    "url = 'https://tip.railway.gov.tw/tra-tip-web/tip'\n",
    "\n",
    "def getTrip():\n",
    "    resp = requests.get('https://tip.railway.gov.tw/tra-tip-web/tip') #'https://tip.railway.gov.tw/tra-tip-web/tip'\n",
    "    \n",
    "    try:\n",
    "        #防錯\n",
    "        if resp.status_code != 200:\n",
    "            print('發生錯誤' + url)\n",
    "\n",
    "        soup = BeautifulSoup(resp.text, 'html5lib')\n",
    "        today = time.strftime('%Y/%m/%d')\n",
    "        station = soup.find(id = 'cityHot').ul.find_all('li')\n",
    "        stationDic = {}\n",
    "\n",
    "        #站名 & 站碼\n",
    "        for i in station:\n",
    "            stationName = i.text.strip()\n",
    "            stationId = i.button['title']\n",
    "            stationDic[stationName] = stationId\n",
    "\n",
    "        #準備傳送資料\n",
    "        csrf = soup.find('input', {'name': '_csrf'})['value']\n",
    "        startStation = input('請輸入出發地：')\n",
    "        endStation = input('請輸入目的地：')\n",
    "\n",
    "        formData = {\n",
    "            '_csrf': csrf,\n",
    "            'trainTypeList': 'ALL',\n",
    "            'transfer': 'ONE',\n",
    "            'startStation': stationDic[startStation],\n",
    "            'endStation': stationDic[endStation],\n",
    "            'rideDate': today,\n",
    "            'startOrEndTime': 'true',\n",
    "            'startTime': '00:00',\n",
    "            'endTime': '23:59',\n",
    "        }\n",
    "\n",
    "        #傳送資料\n",
    "        url = soup.find(id = 'queryForm')['action']\n",
    "        answerResp = requests.post('https://tip.railway.gov.tw/' + url, data = formData)\n",
    "        answerSoup = BeautifulSoup(answerResp.text, 'html5lib')\n",
    "\n",
    "        #從回傳的資料中，取出重點（車次、時間）\n",
    "        trainOption = answerSoup.find_all('tr','trip-column')\n",
    "        for i in trainOption:\n",
    "            trainId = i.a.text\n",
    "            startTrain = i.find_all('span','location')[0].text\n",
    "            endTrain = i.find_all('span','location')[1].text\n",
    "            startTime = i.find_all('td')[1].text\n",
    "            endTime = i.find_all('td')[2].text\n",
    "\n",
    "            print(trainId + '(' + startTrain + '→' + endTrain + ')' + ' 出發時間：' + startTime + ' 抵達時間：' + endTime)\n",
    "\n",
    "    except KeyError:\n",
    "        print('地點輸入錯誤')\n",
    "\n",
    "getTrip()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
